ARG FROM_ROCKYLINUX
FROM rockylinux/rockylinux:${FROM_ROCKYLINUX}
RUN --mount=type=bind,source=./rpm/,target=/rpm/ dnf install --assumeyes /rpm/cfengine.rpm && dnf clean all
RUN find /etc/systemd/system /usr/lib/systemd/system/{basic,multi-user,sysinit}.target.wants -type l -not -lname /dev/null -delete && systemctl mask systemd-logind.service && ln -s /usr/lib/systemd/system/dbus-broker.service /usr/lib/systemd/system/dbus.service
COPY files/cfp_01.service /etc/systemd/system/cfp_01.service
RUN systemctl enable cfp_01
ENTRYPOINT ["/usr/sbin/init"]
CMD ["--show-status=false"]
