= CFP_01: Easy to use CFEngine containers

Provides ready out-of-the-box containers with CFEngine already installed. Intended to be used with containerized tests that requires CFEngine.

== Features

Supported simple `plain` containers:

[cols="1,1"]
|===
|Container name|Based on

|`ghcr.io/teragrep/cfp_01/plain/el8:latest`
|`rockylinux/rockylinux:8`

|`ghcr.io/teragrep/cfp_01/plain/el9:latest`
|`rockylinux/rockylinux:9`
|===

Supported `ipa` containers that extends link:https://github.com/teragrep/ipa_01[`ipa_01`].

[cols="1,1"]
|===
|Container name|Based on

|`ghcr.io/teragrep/cfp_01/ipa/el8:latest`
|`ghcr.io/teragrep/ipa_01/client/el8:1.0.0`

|`ghcr.io/teragrep/cfp_01/ipa/el9:latest`
|`ghcr.io/teragrep/ipa_01/client/el9:1.0.0`
|===

The containers can be pinned to certain releases instead of `:latest`, for example with `:1.0.0`. Full list of versions can be found  in link:https://github.com/orgs/teragrep/packages?repo_name=cfp_01[packages list].

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

All bootstrapping and promise execution logic must be provided by the user.

== How to use

The `plain` containers can be used as if they were like any other normal container.

The `ipa` containers requires link:https://github.com/teragrep/ipa_01?tab=readme-ov-file#how-to-use[some setup].

== Contributing

You can involve yourself with our project by https://github.com/teragrep/cfp_01/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
