= CFP_01: Easy to use CFEngine containers

Provides easy to use, systemd-based containers with CFEngine already installed. Intended to be used with containerized tests that requires CFEngine.

== Features

Easy to run and extend.

Custom entrypoint logic can be inserted and automatically executed without having to worry about creating systemd service files.

Builds both plain `systemd` and link:https://github.com/teragrep/ipa_01[`systemd-ipa`] containers.

Supported plain `systemd` containers:

[cols="1,1"]
|===
|Container name|Based on

|`ghcr.io/teragrep/cfp_01/systemd/el8:latest`
|`rockylinux/rockylinux:8`

|`ghcr.io/teragrep/cfp_01/systemd/el9:latest`
|`rockylinux/rockylinux:9`
|===

Supported `systemd-ipa` containers that extends link:https://github.com/teragrep/ipa_01[`ipa_01`]:

[cols="1,1"]
|===
|Container name|Based on

|`ghcr.io/teragrep/cfp_01/systemd-ipa/el8:latest`
|`ghcr.io/teragrep/ipa_01/client/el8:1.0.0`

|`ghcr.io/teragrep/cfp_01/systemd-ipa/el9:latest`
|`ghcr.io/teragrep/ipa_01/client/el9:1.0.0`
|===

The containers can be pinned to certain releases instead of `:latest`, for example with `:1.0.0`. Full list of versions can be found  in link:https://github.com/orgs/teragrep/packages?repo_name=cfp_01[packages list].

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

All bootstrapping and promise execution logic must be provided by the user.

== How to use

See link:tests/functionality/[`tests/functionality`] for example use.

You can provide `/cfp_01.entrypoint.sh` for the service `cfp_01` to execute on startup if any custom bootstrapping logic is wanted.

The `systemd-ipa` containers requires link:https://github.com/teragrep/ipa_01?tab=readme-ov-file#how-to-use[some setup] and `ipa_01` service to be fully finished before service `cfp_01` is executed.

== Contributing

You can involve yourself with our project by https://github.com/teragrep/cfp_01/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
