name: CI

on: [ push ]

env:
  cfengine_version: 3.21.3

jobs:
  upload:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        from_rockylinux: [ 8, 9 ]
        container_type: [ plain, ipa ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache CFEngine binary
        id: cache-binary
        uses: actions/cache@v5
        with:
          path: rpm
          key: ${{ matrix.from_rockylinux }}-binary

      - name: Download CFEngine
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          mkdir -p "rpm/";
          wget --quiet "https://cfengine-package-repos.s3.amazonaws.com/community_binaries/Community-${cfengine_version}/agent_rhel${{ matrix.from_rockylinux }}_x86_64/cfengine-community-${cfengine_version}-1.el${{ matrix.from_rockylinux }}.x86_64.rpm" --output-document "rpm/cfengine.rpm";

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build containers
        uses: docker/build-push-action@v7
        with:
          push: false
          file: "Dockerfile.${{ matrix.container_type }}"
          build-args: |
            FROM_ROCKYLINUX="${{ matrix.from_rockylinux }}"
